name: "Mera pehla action workflow"

on:
  pull_request: 
    branches:
      - main
  push: 
    branches: 
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform-init-plan:
    name: terraform initwa
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
                
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0
                    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: dd01b263-5ece-426e-911c-32d8138bd329
          tenant-id: ec84cc3b-8d4d-4362-b666-466802d7ba4e
          subscription-id: 85bce315-2d40-4002-a3d1-b7f28202855c
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: Parent_module/Dev
  
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: Parent_module/Dev
  
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: Parent_module/Dev
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: Parent_module/Dev
          
  
  terraform-apply:
    runs-on: ubuntu-latest
    if: github.ref == 'ref/heads/main'
    needs: terraform-init-plan
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0
                       
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: dd01b263-5ece-426e-911c-32d8138bd329
          tenant-id: ec84cc3b-8d4d-4362-b666-466802d7ba4e
          subscription-id: 85bce315-2d40-4002-a3d1-b7f28202855c

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: Parent_module/Dev
          
      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: Parent_module/Dev
